version: '3.3'
services:
  https:
    image: nginx
    container_name: medic-nginx
    ports:
     - 443:443
    volumes:
     - ./https/nginx-ssl-proxy.conf:/etc/nginx/conf.d/default.conf
    secrets:
     - nginx.crt
     - nginx.key
    network_mode: host

  dns:
    container_name: medic-dns
    image: emsi/bind9:latest
    ports:
     - 53:53/udp
     - 53:53/tcp
    volumes:
     - ./dns/named.conf.local:/etc/bind/named.conf.local
     - ./deploy/db.medic.dev:/etc/bind/db.medic.dev

secrets:
  nginx.crt:
    file: "./https/certificate.crt"
  nginx.key:
    file: "./https/certificate.key"
  